### PR TITLE
switch to new registrator and drop CI support for julia 0.7

### PR DESCRIPTION
**Pull request by johnnychen94**
more details in https://github.com/JuliaImages/Images.jl/issues/798

Blocking PRs/repos:

- [x] https://github.com/JuliaImages/Images.jl/pull/800
- [x] https://github.com/Evizero/ReferenceTests.jl/pull/22
- [x] https://github.com/JuliaImages/ImageInTerminal.jl/pull/20
- [x] https://github.com/JuliaIO/ImageMagick.jl/pull/152

### CODE REVIEW

**Comment by ianshmean** [comment]
Seems like things are progressing! Thanks! Just FYI, `ImageTransformations` seems to be the (hopefully last) block for `VideoIO` CI

```
ERROR: Unsatisfiable requirements detected for package ImageTransformations [02fcd773]:
 ImageTransformations [02fcd773] log:
 ├─possible versions are: [0.0.1, 0.1.0, 0.2.0-0.2.2, 0.3.0-0.3.1, 0.4.0-0.4.2, 0.5.0-0.5.2, 0.6.0, 0.7.0-0.7.2] or uninstalled
 ├─restricted by compatibility requirements with ImageCore [a09fc81d] to versions: uninstalled
 │ └─ImageCore [a09fc81d] log:
 │   ├─possible versions are: [0.0.1-0.0.5, 0.1.0-0.1.5, 0.2.0-0.2.1, 0.3.0-0.3.3, 0.4.0-0.4.1, 0.5.0, 0.6.0, 0.7.0-0.7.4, 0.8.0-0.8.2] or uninstalled
 │   ├─restricted to versions * by VideoIO [d6d074c3], leaving only versions [0.0.1-0.0.5, 0.1.0-0.1.5, 0.2.0-0.2.1, 0.3.0-0.3.3, 0.4.0-0.4.1, 0.5.0, 0.6.0, 0.7.0-0.7.4, 0.8.0-0.8.2]
 │   │ └─VideoIO [d6d074c3] log:
 │   │   ├─possible versions are: 0.5.4 or uninstalled
 │   │   └─VideoIO [d6d074c3] is fixed to version 0.5.4
 │   └─restricted to versions 0.8.2 by an explicit requirement, leaving only versions 0.8.2
 └─restricted by compatibility requirements with Images [916415d5] to versions: [0.2.2, 0.3.0-0.3.1, 0.4.0-0.4.2, 0.5.0-0.5.2, 0.6.0, 0.7.0-0.7.2] — no versions left
   └─Images [916415d5] log:
     ├─possible versions are: [0.2.0-0.2.50, 0.3.0-0.3.3, 0.4.0-0.4.50, 0.5.0-0.5.14, 0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.1, 0.11.0-0.11.5, 0.12.0, 0.13.0, 0.14.0, 0.15.0-0.15.1, 0.16.0-0.16.1, 0.17.0-0.17.3, 0.18.0] or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions [0.2.0-0.2.50, 0.3.0-0.3.3, 0.4.0-0.4.50, 0.5.0-0.5.14, 0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.1, 0.11.0-0.11.5, 0.12.0, 0.13.0, 0.14.0, 0.15.0-0.15.1, 0.16.0-0.16.1, 0.17.0-0.17.3, 0.18.0]
     ├─restricted by compatibility requirements with ImageCore [a09fc81d] to versions: [0.2.0-0.2.50, 0.3.0-0.3.3, 0.4.0-0.4.50, 0.5.0-0.5.14, 0.18.0] or uninstalled, leaving only versions: [0.2.0-0.2.50, 0.3.0-0.3.3, 0.4.0-0.4.50, 0.5.0-0.5.14, 0.18.0]
     │ └─ImageCore [a09fc81d] log: see above
     └─restricted by julia compatibility requirements to versions: [0.15.0-0.15.1, 0.16.0-0.16.1, 0.17.0-0.17.3, 0.18.0] or uninstalled, leaving only versions: 0.18.0
```

**Comment by timholy** [comment]
This is turning into a game of whac-a-mole. Now it's ImageMorphology: https://github.com/JuliaRegistries/General/pull/390

**Comment by johnnychen94** [comment]
Is it because I used a wrong upgrade strategy, or it’s a unavoidable issue switching from old system?

Johnny
On Apr 29, 2019, 02:56 +0800, Tim Holy <notifications@github.com>, wrote:

This is turning into a game of whac-a-mole. Now it's ImageMorphology: JuliaRegistries/General#390<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJuliaRegistries%2FGeneral%2Fpull%2F390&data=02%7C01%7C%7C3cb82800d7f84c8ccd4008d6cc0b30f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636920745773233751&sdata=53dH%2BARumS0Ahmo6ag8zYfKXiAo%2FNBVTXcrWVrw6UB0%3D&reserved=0>

**Comment by timholy** [comment]
Not your fault at all. I was hoping to go through "normal channels" but the right fix was to modify the registry itself. Thanks to @ianshmean! https://github.com/JuliaRegistries/General/pull/392 and https://github.com/JuliaRegistries/General/pull/412

**Pull request merged**
