### PR TITLE
Adds swirl function

### PR DESCRIPTION
**Pull request by paniash**
This PR adds a swirl as a standard function.

Relevent issues: #133

### CODE REVIEW

**Comment by johnnychen94** [comment]
To make it a standard library function, we need to:

- [ ] polish the API:
  - should we take the scikit-image version, or invent our own?
  - The example swirl function uses the center point as the swirl center `x0`, I think we can let users decide where the swirl center is.
- [ ] add tests
- [ ] add documentation

You can take a look at `imrotate` function as an example. For tests purposes, we can use ReferenceTests.

**Comment by johnnychen94** [comment]
Is there any plan to finish this PR?

**Comment by paniash** [comment]
Hi! Sorry, life's gotten in the way. Please feel free to go ahead. :-)

**Comment by johnnychen94** [comment]
Thanks. I'm closing this in favor of #146

**Pull request closed without merging**
