### PR TITLE
update REQUIRE

### PR DESCRIPTION
**Pull request by Evizero**
The tests still don't run locally for me because `recenter` is not defined. I am guessing WIP?

### CODE REVIEW

**Comment by timholy** [comment]
You need master on `StaticArrays`, `Rotations`, and `CoordinateTransformations`:
- https://github.com/JuliaArrays/StaticArrays.jl/pull/49
- https://github.com/FugroRoames/Rotations.jl/pull/13
- https://github.com/FugroRoames/CoordinateTransformations.jl/pull/21

**Comment by timholy** [comment]
Thanks!

**Comment by andyferris** [comment]
Yes it is about time I tag these.

**Comment by Evizero** [comment]
@timholy Thanks, that works. 

I take it all the warnings that the tests cause, such as:

```
WARNING: Method definition height(AbstractArray) in module ImageCore 
at /home/<username>/.julia/v0.5/ImageCore/src/traits.jl:86 overwritten in 
module Images at /home/<username>/.julia/v0.5/Images/src/core.jl:1236.
```

are expected until the transition to the new Images is complete?

**Pull request merged**
